using Avalonia;
using Avalonia.Controls;
namespace Wall_E_Pixel.ViewModels;

public partial class MainWindowViewModel : ViewModelBase
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }

    // in auto-generated by Avalonia.NameGenerator MainWindow.g.cs:
    partial class MainWindow
    {
        // ...
        public void InitializeComponent(bool loadXaml = true, bool attachDevTools = true)
        {
            // ...
#if DEBUG
            if (attachDevTools)
            {
                this.AttachDevTools();
            }
#endif
            // ...
        }
    }
    public string Greeting { get; } = "Welcome to Avalonia!";
}
